### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by hujingyucd** [amirhertz/spaghetti#1]
Thanks for your fancy work! And I notice that in your paper's experiment setting, the Generation task includes "table", "chair", "airplane". And now since the pretrained model for table and airplane has been released, will the pretrained model for "table" be released? Really appreciate it if it can be released. Thanks.

**Comment by amirhertz** [comment]
The weights for the table model  can be download from [here](https://drive.google.com/file/d/1C82phZYsuVY8JmLvWNzV2L6Dfc2-K5mq/view?usp=sharing).
Thanks

**Comment by hujingyucd** [comment]
Thanks for your help!
