### ISSUE TITLE
Segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by EricLee0224** [amirhertz/spaghetti#6]
Editing shapes in implicit space is really cool, and I really want to try the demo!  Unfortunately, I got everything fixed, but I encountered this problem: 
![2d0ffdb1cf1482d22de7945aecfd3af](https://user-images.githubusercontent.com/96402054/226359375-e6c85408-8061-426d-878f-18a69b8f808f.png)
(In Linux env)
Is there any good way to solve it? Thank you！

**Comment by flanza88** [comment]
Me too ,bro
![Snipaste_2024-11-07_15-07-12](https://github.com/user-attachments/assets/140770d3-81cb-4caf-9d1f-a494a2097ec4)

**Comment by EricLee0224** [comment]
You may need to ensure that your GPU servers are available for GUI. Or you can use MobaXterm to open the X server , and set "export DISPLAY=localhost:0.0" (or 10.0, 11.0).
